/**********************************************************************

	--- Qt Architect generated file ---

	File: Format_dlgData.h
	Last generated: Tue Mar 9 11:13:05 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef Format_dlgData_included
#define Format_dlgData_included

#include <qdialog.h>
#include <qcombo.h>

class Format_dlgData : public QDialog
{
    Q_OBJECT

public:

    Format_dlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~Format_dlgData();

public slots:


protected slots:

    virtual void format_click();
    virtual void cancel_click();

protected:
    QComboBox* fs_type;

};

#endif // Format_dlgData_included
