/**********************************************************************

	--- Qt Architect generated file ---

	File: Format_dlgData.cc
	Last generated: Tue Mar 9 11:13:05 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "Format_dlgData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

Format_dlgData::Format_dlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 20480 )
{
	fs_type = new QComboBox( FALSE, this, "ComboBox_1" );
	fs_type->setGeometry( 190, 30, 100, 30 );
	fs_type->setMinimumSize( 100, 30 );
	fs_type->setMaximumSize( 100, 30 );
	fs_type->setFocusPolicy( QWidget::StrongFocus );
	fs_type->setBackgroundMode( QWidget::PaletteBackground );
	fs_type->setFontPropagation( QWidget::AllChildren );
	fs_type->setPalettePropagation( QWidget::AllChildren );
	fs_type->setSizeLimit( 10 );
	fs_type->setAutoResize( FALSE );
	fs_type->insertItem( "ext2" );
	fs_type->insertItem( "dos" );

	QLabel* qtarch_Label_1;
	qtarch_Label_1 = new QLabel( this, "Label_1" );
	qtarch_Label_1->setGeometry( 90, 30, 100, 30 );
	qtarch_Label_1->setMinimumSize( 100, 30 );
	qtarch_Label_1->setMaximumSize( 100, 30 );
	qtarch_Label_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_1->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_1->setText( "File system type:" );
	qtarch_Label_1->setAlignment( 289 );
	qtarch_Label_1->setMargin( -1 );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 30, 90, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 100, 30 );
	qtarch_PushButton_1->setMaximumSize( 100, 30 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(format_click()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( "Format" );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 240, 90, 100, 30 );
	qtarch_PushButton_2->setMinimumSize( 100, 30 );
	qtarch_PushButton_2->setMaximumSize( 100, 30 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(cancel_click()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setText( "Cancel" );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );

	resize( 380,150 );
	setMinimumSize( 380, 150 );
	setMaximumSize( 380, 150 );
}


Format_dlgData::~Format_dlgData()
{
}
void Format_dlgData::format_click()
{
}
void Format_dlgData::cancel_click()
{
}
