/**********************************************************************

	--- Qt Architect generated file ---

	File: main_dlgData.cc
	Last generated: Wed Mar 10 22:51:55 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "main_dlgData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbttngrp.h>
#include <qpushbt.h>

main_dlgData::main_dlgData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, FALSE, 0 )
{
	QButtonGroup* qtarch_ButtonGroup_1;
	qtarch_ButtonGroup_1 = new QButtonGroup( this, "ButtonGroup_1" );
	qtarch_ButtonGroup_1->setGeometry( 30, 90, 200, 150 );
	qtarch_ButtonGroup_1->setMinimumSize( 200, 150 );
	qtarch_ButtonGroup_1->setMaximumSize( 200, 150 );
	qtarch_ButtonGroup_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_1->setFontPropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_1->setFrameStyle( 49 );
	qtarch_ButtonGroup_1->setTitle( "Mode Selector" );
	qtarch_ButtonGroup_1->setAlignment( 1 );

	rw_Button = new QRadioButton( this, "RadioButton_1" );
	rw_Button->setGeometry( 40, 110, 180, 30 );
	rw_Button->setMinimumSize( 180, 30 );
	rw_Button->setMaximumSize( 180, 30 );
	rw_Button->setFocusPolicy( QWidget::TabFocus );
	rw_Button->setBackgroundMode( QWidget::PaletteBackground );
	rw_Button->setFontPropagation( QWidget::NoChildren );
	rw_Button->setPalettePropagation( QWidget::NoChildren );
	rw_Button->setText( "Read Write (rw)" );
	rw_Button->setAutoRepeat( FALSE );
	rw_Button->setAutoResize( FALSE );

	pw_Button = new QRadioButton( this, "RadioButton_2" );
	pw_Button->setGeometry( 40, 200, 180, 30 );
	pw_Button->setMinimumSize( 180, 30 );
	pw_Button->setMaximumSize( 180, 30 );
	pw_Button->setFocusPolicy( QWidget::TabFocus );
	pw_Button->setBackgroundMode( QWidget::PaletteBackground );
	pw_Button->setFontPropagation( QWidget::NoChildren );
	pw_Button->setPalettePropagation( QWidget::NoChildren );
	pw_Button->setText( "Password Protection (pw)" );
	pw_Button->setAutoRepeat( FALSE );
	pw_Button->setAutoResize( FALSE );

	pwro_Button = new QRadioButton( this, "RadioButton_3" );
	pwro_Button->setGeometry( 40, 170, 180, 30 );
	pwro_Button->setMinimumSize( 180, 30 );
	pwro_Button->setMaximumSize( 180, 30 );
	pwro_Button->setFocusPolicy( QWidget::TabFocus );
	pwro_Button->setBackgroundMode( QWidget::PaletteBackground );
	pwro_Button->setFontPropagation( QWidget::NoChildren );
	pwro_Button->setPalettePropagation( QWidget::NoChildren );
	pwro_Button->setText( "Password Read Only (pwro)" );
	pwro_Button->setAutoRepeat( FALSE );
	pwro_Button->setAutoResize( FALSE );

	ro_Button = new QRadioButton( this, "RadioButton_4" );
	ro_Button->setGeometry( 40, 140, 180, 30 );
	ro_Button->setMinimumSize( 180, 30 );
	ro_Button->setMaximumSize( 180, 30 );
	ro_Button->setFocusPolicy( QWidget::TabFocus );
	ro_Button->setBackgroundMode( QWidget::PaletteBackground );
	ro_Button->setFontPropagation( QWidget::NoChildren );
	ro_Button->setPalettePropagation( QWidget::NoChildren );
	ro_Button->setText( "Read Only (ro)" );
	ro_Button->setAutoRepeat( FALSE );
	ro_Button->setAutoResize( FALSE );

	QLabel* qtarch_Label_3;
	qtarch_Label_3 = new QLabel( this, "Label_3" );
	qtarch_Label_3->setGeometry( 270, 90, 100, 30 );
	qtarch_Label_3->setMinimumSize( 100, 30 );
	qtarch_Label_3->setMaximumSize( 100, 30 );
	qtarch_Label_3->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_3->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_3->setText( "Device:" );
	qtarch_Label_3->setAlignment( 289 );
	qtarch_Label_3->setMargin( -1 );

	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 270, 180, 100, 30 );
	qtarch_Label_4->setMinimumSize( 100, 30 );
	qtarch_Label_4->setMaximumSize( 100, 30 );
	qtarch_Label_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_4->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_4->setText( "Current mode:" );
	qtarch_Label_4->setAlignment( 289 );
	qtarch_Label_4->setMargin( -1 );

	cur_mode = new QLabel( this, "Label_5" );
	cur_mode->setGeometry( 270, 210, 100, 30 );
	cur_mode->setMinimumSize( 100, 30 );
	cur_mode->setMaximumSize( 100, 30 );
	{
		QColorGroup normal( QColor( QRgb(0) ), QColor( QRgb(16777215) ), QColor( QRgb(16777215) ), QColor( QRgb(8421504) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QColorGroup disabled( QColor( QRgb(8421504) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(8421504) ), QColor( QRgb(10789024) ), QColor( QRgb(8421504) ), QColor( QRgb(12632256) ) );
		QColorGroup active( QColor( QRgb(0) ), QColor( QRgb(12632256) ), QColor( QRgb(16777215) ), QColor( QRgb(8421504) ), QColor( QRgb(10789024) ), QColor( QRgb(0) ), QColor( QRgb(16777215) ) );
		QPalette palette( normal, disabled, active );
		cur_mode->setPalette( palette );
	}
	cur_mode->setFocusPolicy( QWidget::NoFocus );
	cur_mode->setBackgroundMode( QWidget::PaletteBackground );
	cur_mode->setFontPropagation( QWidget::NoChildren );
	cur_mode->setPalettePropagation( QWidget::NoChildren );
	cur_mode->setFrameStyle( 51 );
	cur_mode->setLineWidth( 2 );
	cur_mode->setText( "" );
	cur_mode->setAlignment( 289 );
	cur_mode->setMargin( -1 );

	icona = new QLabel( this, "Label_6" );
	icona->setGeometry( 130, 40, 32, 32 );
	icona->setMinimumSize( 32, 32 );
	icona->setMaximumSize( 32, 32 );
	icona->setFocusPolicy( QWidget::NoFocus );
	icona->setFontPropagation( QWidget::NoChildren );
	icona->setPalettePropagation( QWidget::NoChildren );
	icona->setText( "" );
	icona->setAlignment( 289 );
	icona->setMargin( -1 );

	QLabel* qtarch_Label_7;
	qtarch_Label_7 = new QLabel( this, "Label_7" );
	qtarch_Label_7->setGeometry( 170, 40, 100, 30 );
	qtarch_Label_7->setMinimumSize( 0, 0 );
	qtarch_Label_7->setMaximumSize( 32767, 32767 );
	{
		QFont font( "helvetica", 18, 50, 1 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		qtarch_Label_7->setFont( font );
	}
	qtarch_Label_7->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_7->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_7->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_7->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_7->setText( "ZipTools!" );
	qtarch_Label_7->setAlignment( 289 );
	qtarch_Label_7->setMargin( -1 );

	QPushButton* qtarch_PushButton_7;
	qtarch_PushButton_7 = new QPushButton( this, "PushButton_7" );
	qtarch_PushButton_7->setGeometry( 30, 270, 100, 30 );
	qtarch_PushButton_7->setMinimumSize( 100, 30 );
	qtarch_PushButton_7->setMaximumSize( 100, 30 );
	connect( qtarch_PushButton_7, SIGNAL(clicked()), SLOT(ch_click()) );
	qtarch_PushButton_7->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_7->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_7->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_7->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_7->setText( "Change Mode" );
	qtarch_PushButton_7->setAutoRepeat( FALSE );
	qtarch_PushButton_7->setAutoResize( FALSE );

	format_Button = new QPushButton( this, "PushButton_8" );
	format_Button->setGeometry( 270, 270, 100, 30 );
	format_Button->setMinimumSize( 100, 30 );
	format_Button->setMaximumSize( 100, 30 );
	connect( format_Button, SIGNAL(clicked()), SLOT(format_click()) );
	format_Button->setFocusPolicy( QWidget::TabFocus );
	format_Button->setBackgroundMode( QWidget::PaletteBackground );
	format_Button->setFontPropagation( QWidget::NoChildren );
	format_Button->setPalettePropagation( QWidget::NoChildren );
	format_Button->setText( "Format" );
	format_Button->setAutoRepeat( FALSE );
	format_Button->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_10;
	qtarch_PushButton_10 = new QPushButton( this, "PushButton_10" );
	qtarch_PushButton_10->setGeometry( 150, 270, 100, 30 );
	qtarch_PushButton_10->setMinimumSize( 0, 0 );
	qtarch_PushButton_10->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_10, SIGNAL(clicked()), SLOT(ej_click()) );
	qtarch_PushButton_10->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_10->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_10->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_10->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_10->setText( "Eject" );
	qtarch_PushButton_10->setAutoRepeat( FALSE );
	qtarch_PushButton_10->setAutoResize( FALSE );

	mbar = new QMenuBar( this, "MenuBar_1" );
	mbar->setGeometry( 0, 0, 400, 30 );
	mbar->setMinimumSize( 0, 30 );
	mbar->setMaximumSize( 32767, 30 );
	mbar->setFocusPolicy( QWidget::NoFocus );
	mbar->setBackgroundMode( QWidget::PaletteBackground );
	mbar->setFontPropagation( QWidget::NoChildren );
	mbar->setPalettePropagation( QWidget::NoChildren );
	mbar->setFrameStyle( 34 );
	mbar->setLineWidth( 2 );

	dev_name = new QComboBox( FALSE, this, "ComboBox_1" );
	dev_name->setGeometry( 270, 120, 100, 30 );
	dev_name->setMinimumSize( 100, 30 );
	dev_name->setMaximumSize( 100, 30 );
	connect( dev_name, SIGNAL(activated(const char*)), SLOT(dev_changed(const char*)) );
	dev_name->setFocusPolicy( QWidget::StrongFocus );
	dev_name->setBackgroundMode( QWidget::PaletteBackground );
	dev_name->setFontPropagation( QWidget::AllChildren );
	dev_name->setPalettePropagation( QWidget::AllChildren );
	dev_name->setSizeLimit( 8 );
	dev_name->setAutoResize( FALSE );
	dev_name->insertItem( "/dev/sda" );
	dev_name->insertItem( "/dev/sdb" );
	dev_name->insertItem( "/dev/sdc" );
	dev_name->insertItem( "/dev/sdd" );
	dev_name->insertItem( "/dev/sde" );
	dev_name->insertItem( "/dev/sdf" );
	dev_name->insertItem( "/dev/sdg" );
	dev_name->insertItem( "/dev/sdh" );
	dev_name->insertItem( "--device--" );

	qtarch_ButtonGroup_1->insert( rw_Button );
	qtarch_ButtonGroup_1->insert( pw_Button );
	qtarch_ButtonGroup_1->insert( pwro_Button );
	qtarch_ButtonGroup_1->insert( ro_Button );

	resize( 400,320 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


main_dlgData::~main_dlgData()
{
}
void main_dlgData::ch_click()
{
}
void main_dlgData::format_click()
{
}
void main_dlgData::ej_click()
{
}
void main_dlgData::dev_changed(const char*)
{
}
