/**********************************************************************

	--- Qt Architect generated file ---

	File: main_dlgData.h
	Last generated: Wed Mar 10 22:51:55 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef main_dlgData_included
#define main_dlgData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qmenubar.h>
#include <qpushbt.h>
#include <qradiobt.h>
#include <qcombo.h>

class main_dlgData : public QDialog
{
    Q_OBJECT

public:

    main_dlgData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~main_dlgData();

public slots:


protected slots:

    virtual void ej_click();
    virtual void format_click();
    virtual void dev_changed(const char*);
    virtual void ch_click();

protected:
    QRadioButton* rw_Button;
    QRadioButton* pw_Button;
    QRadioButton* pwro_Button;
    QRadioButton* ro_Button;
    QLabel* cur_mode;
    QLabel* icona;
    QPushButton* format_Button;
    QMenuBar* mbar;
    QComboBox* dev_name;

};

#endif // main_dlgData_included
