/**********************************************************************

	--- Qt Architect generated file ---

	File: new_passData.h
	Last generated: Wed Mar 10 22:49:27 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef new_passData_included
#define new_passData_included

#include <qdialog.h>
#include <qlined.h>

class new_passData : public QDialog
{
    Q_OBJECT

public:

    new_passData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~new_passData();

public slots:


protected slots:

    virtual void cancel_click();
    virtual void ok_click();

protected:
    QLineEdit* pass;
    QLineEdit* repass;

};

#endif // new_passData_included
