/**********************************************************************

	--- Qt Architect generated file ---

	File: new_passData.cc
	Last generated: Wed Mar 10 22:49:27 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "new_passData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

new_passData::new_passData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QLabel* qtarch_Label_1;
	qtarch_Label_1 = new QLabel( this, "Label_1" );
	qtarch_Label_1->setGeometry( 20, 20, 140, 30 );
	qtarch_Label_1->setMinimumSize( 140, 30 );
	qtarch_Label_1->setMaximumSize( 140, 30 );
	qtarch_Label_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_1->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_1->setText( "Type the new password:" );
	qtarch_Label_1->setAlignment( 289 );
	qtarch_Label_1->setMargin( -1 );

	pass = new QLineEdit( this, "LineEdit_1" );
	pass->setGeometry( 20, 50, 350, 30 );
	pass->setMinimumSize( 350, 30 );
	pass->setMaximumSize( 350, 30 );
	connect( pass, SIGNAL(returnPressed()), SLOT(ok_click()) );
	pass->setFocusPolicy( QWidget::StrongFocus );
	pass->setBackgroundMode( QWidget::PaletteBase );
	pass->setFontPropagation( QWidget::NoChildren );
	pass->setPalettePropagation( QWidget::NoChildren );
	pass->setText( "" );
	pass->setMaxLength( 33 );
	pass->setEchoMode( QLineEdit::Password );
	pass->setFrame( TRUE );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 20, 180, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 100, 30 );
	qtarch_PushButton_1->setMaximumSize( 100, 30 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(ok_click()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( "Ok" );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 270, 180, 100, 30 );
	qtarch_PushButton_2->setMinimumSize( 100, 30 );
	qtarch_PushButton_2->setMaximumSize( 100, 30 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(cancel_click()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setText( "Cancel" );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );

	repass = new QLineEdit( this, "LineEdit_2" );
	repass->setGeometry( 20, 130, 350, 30 );
	repass->setMinimumSize( 350, 30 );
	repass->setMaximumSize( 350, 30 );
	connect( repass, SIGNAL(returnPressed()), SLOT(ok_click()) );
	repass->setFocusPolicy( QWidget::StrongFocus );
	repass->setBackgroundMode( QWidget::PaletteBase );
	repass->setFontPropagation( QWidget::NoChildren );
	repass->setPalettePropagation( QWidget::NoChildren );
	repass->setText( "" );
	repass->setMaxLength( 33 );
	repass->setEchoMode( QLineEdit::Password );
	repass->setFrame( TRUE );

	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 20, 100, 100, 30 );
	qtarch_Label_4->setMinimumSize( 0, 0 );
	qtarch_Label_4->setMaximumSize( 32767, 32767 );
	qtarch_Label_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_4->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_4->setText( "Again:" );
	qtarch_Label_4->setAlignment( 289 );
	qtarch_Label_4->setMargin( -1 );

	resize( 390,230 );
	setMinimumSize( 390, 230 );
	setMaximumSize( 390, 230 );
}


new_passData::~new_passData()
{
}
void new_passData::ok_click()
{
}
void new_passData::cancel_click()
{
}
