/**********************************************************************

	--- Qt Architect generated file ---

	File: old_passData.h
	Last generated: Tue Mar 9 11:13:25 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef old_passData_included
#define old_passData_included

#include <qdialog.h>
#include <qlined.h>

class old_passData : public QDialog
{
    Q_OBJECT

public:

    old_passData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~old_passData();

public slots:


protected slots:

    virtual void cancel_click();
    virtual void ok_click();

protected:
    QLineEdit* pass;

};

#endif // old_passData_included
