/**********************************************************************

	--- Qt Architect generated file ---

	File: old_passData.cc
	Last generated: Tue Mar 9 11:13:25 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "old_passData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

old_passData::old_passData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 20, 100, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 100, 30 );
	qtarch_PushButton_1->setMaximumSize( 100, 30 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(ok_click()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( "Ok" );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 270, 100, 100, 30 );
	qtarch_PushButton_2->setMinimumSize( 100, 30 );
	qtarch_PushButton_2->setMaximumSize( 100, 30 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(cancel_click()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setText( "Cancel" );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );

	pass = new QLineEdit( this, "LineEdit_1" );
	pass->setGeometry( 20, 50, 350, 30 );
	pass->setMinimumSize( 350, 30 );
	pass->setMaximumSize( 350, 30 );
	connect( pass, SIGNAL(returnPressed()), SLOT(ok_click()) );
	pass->setFocusPolicy( QWidget::StrongFocus );
	pass->setBackgroundMode( QWidget::PaletteBase );
	pass->setFontPropagation( QWidget::NoChildren );
	pass->setPalettePropagation( QWidget::NoChildren );
	pass->setText( "" );
	pass->setMaxLength( 33 );
	pass->setEchoMode( QLineEdit::Password );
	pass->setFrame( TRUE );

	QLabel* qtarch_Label_1;
	qtarch_Label_1 = new QLabel( this, "Label_1" );
	qtarch_Label_1->setGeometry( 20, 20, 140, 30 );
	qtarch_Label_1->setMinimumSize( 140, 30 );
	qtarch_Label_1->setMaximumSize( 140, 30 );
	qtarch_Label_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_1->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_1->setText( "Type the old password:" );
	qtarch_Label_1->setAlignment( 289 );
	qtarch_Label_1->setMargin( -1 );

	resize( 390,150 );
	setMinimumSize( 390, 160 );
	setMaximumSize( 390, 160 );
}


old_passData::~old_passData()
{
}
void old_passData::ok_click()
{
}
void old_passData::cancel_click()
{
}
